// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Planura.Infrastructure.Persistence;

#nullable disable

namespace Planura.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlanuraDbContext))]
    partial class PlanuraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("role_name_index")
                        .HasFilter("[normalized_name] IS NOT NULL");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.AiEventVisualization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("EventPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_plan_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model_used");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt");

                    b.HasKey("Id")
                        .HasName("pk_ai_event_visualizations");

                    b.HasIndex("EventPlanId")
                        .HasDatabaseName("ix_ai_event_visualizations_event_plan_id");

                    b.ToTable("ai_event_visualizations");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.AiInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("EventPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_plan_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("theme");

                    b.HasKey("Id")
                        .HasName("pk_ai_invitations");

                    b.HasIndex("EventPlanId")
                        .HasDatabaseName("ix_ai_invitations_event_plan_id");

                    b.ToTable("ai_invitations");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("ar")
                        .HasColumnName("preferred_language");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index")
                        .HasFilter("[normalized_user_name] IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.BookingRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AgreedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("agreed_price");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("cancelled_at");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_message");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisputeStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("dispute_status");

                    b.Property<DateTimeOffset?>("DisputedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("disputed_at");

                    b.Property<long?>("DisputedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("disputed_by_user_id");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<long>("EventPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_plan_id");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("int")
                        .HasColumnName("guest_count");

                    b.Property<DateTimeOffset?>("PaymentReminderSentAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("payment_reminder_sent_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unpaid")
                        .HasColumnName("payment_status");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("resolved_at");

                    b.Property<long?>("ResolvedByAdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_by_admin_id");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.Property<long?>("VendorPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_package_id");

                    b.Property<string>("VendorResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vendor_response");

                    b.HasKey("Id")
                        .HasName("pk_booking_requests");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_booking_requests_client_id");

                    b.HasIndex("DisputedByUserId")
                        .HasDatabaseName("ix_booking_requests_disputed_by_user_id");

                    b.HasIndex("EventPlanId")
                        .HasDatabaseName("ix_booking_requests_event_plan_id");

                    b.HasIndex("ResolvedByAdminId")
                        .HasDatabaseName("ix_booking_requests_resolved_by_admin_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_booking_requests_status");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_booking_requests_vendor_id");

                    b.HasIndex("VendorPackageId")
                        .HasDatabaseName("ix_booking_requests_vendor_package_id");

                    b.ToTable("booking_requests");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_request_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("new_status");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("previous_status");

                    b.HasKey("Id")
                        .HasName("pk_booking_status_history");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_booking_status_history_booking_request_id");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_booking_status_history_changed_by_user_id");

                    b.ToTable("booking_status_history");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_user_id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.EventPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BudgetTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("budget_total");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_type");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("int")
                        .HasColumnName("guest_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<string>("StyleNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("style_notes");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id")
                        .HasName("pk_event_plans");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_event_plans_client_id");

                    b.ToTable("event_plans");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.EventPlanItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("EstimatedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("estimated_price");

                    b.Property<long>("EventPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_plan_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.Property<long?>("VendorPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_package_id");

                    b.HasKey("Id")
                        .HasName("pk_event_plan_items");

                    b.HasIndex("EventPlanId")
                        .HasDatabaseName("ix_event_plan_items_event_plan_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_event_plan_items_vendor_id");

                    b.HasIndex("VendorPackageId")
                        .HasDatabaseName("ix_event_plan_items_vendor_package_id");

                    b.ToTable("event_plan_items");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("data_json");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("amount");

                    b.Property<long>("BookingRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_request_id");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gateway_reference");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("payment_method");

                    b.Property<string>("RefundReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refund_reason");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("refunded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_payments_booking_request_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_payments_client_id");

                    b.HasIndex("GatewayReference")
                        .HasDatabaseName("ix_payments_gateway_reference");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_payments_vendor_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.PortfolioLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("platform");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_links");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_portfolio_links_vendor_id");

                    b.ToTable("portfolio_links");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.PortfolioMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("int")
                        .HasColumnName("duration_sec");

                    b.Property<int?>("FileSizeKb")
                        .HasColumnType("int")
                        .HasColumnName("file_size_kb");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_media");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_portfolio_media_vendor_id");

                    b.ToTable("portfolio_media");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_request_id");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("BookingRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_booking_request_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_reviews_client_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_reviews_vendor_id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.ReviewResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_review_responses");

                    b.HasIndex("ReviewId")
                        .IsUnique()
                        .HasDatabaseName("ix_review_responses_review_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_review_responses_vendor_id");

                    b.ToTable("review_responses");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_service_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_service_categories_slug");

                    b.ToTable("service_categories");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Vendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<decimal>("AvgRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("avg_rating");

                    b.Property<string>("BusinessDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_description");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("business_name");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<int>("TotalCompletedBookings")
                        .HasColumnType("int")
                        .HasColumnName("total_completed_bookings");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("VendorType")
                        .HasColumnType("int")
                        .HasColumnName("vendor_type");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("unverified")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_vendors_category_id");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_vendors_city");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_user_id");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_vendors_verification_status");

                    b.ToTable("vendors");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BookingRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_request_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("end_at");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("hold_expires_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_availability");

                    b.HasIndex("BookingRequestId")
                        .HasDatabaseName("ix_vendor_availability_booking_request_id");

                    b.HasIndex("VendorId", "StartAt")
                        .IsUnique()
                        .HasDatabaseName("idx_vendor_availability_no_double_hold")
                        .HasFilter("([status] IN ('Held', 'Booked'))");

                    b.ToTable("vendor_availability");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("EGP")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Includes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("includes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxGuests")
                        .HasColumnType("int")
                        .HasColumnName("max_guests");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_packages");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_vendor_packages_vendor_id");

                    b.ToTable("vendor_packages");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorVerification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("reviewed_at");

                    b.Property<long?>("ReviewedByAdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("reviewed_by_admin_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset?>("TrustedSince")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("trusted_since");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_verifications");

                    b.HasIndex("ReviewedByAdminId")
                        .HasDatabaseName("ix_vendor_verifications_reviewed_by_admin_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_vendor_verifications_vendor_id");

                    b.ToTable("vendor_verifications");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorVerificationDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<long>("VendorVerificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_verification_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_verification_documents");

                    b.HasIndex("VendorVerificationId")
                        .HasDatabaseName("ix_vendor_verification_documents_vendor_verification_id");

                    b.ToTable("vendor_verification_documents");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorVerificationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("ChangedByAdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by_admin_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("new_status");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("previous_status");

                    b.Property<long>("VendorVerificationId")
                        .HasColumnType("bigint")
                        .HasColumnName("vendor_verification_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_verification_history");

                    b.HasIndex("ChangedByAdminId")
                        .HasDatabaseName("ix_vendor_verification_history_changed_by_admin_id");

                    b.HasIndex("VendorVerificationId")
                        .HasDatabaseName("ix_vendor_verification_history_vendor_verification_id");

                    b.ToTable("vendor_verification_history");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.AiEventVisualization", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.EventPlan", "EventPlan")
                        .WithMany("AiEventVisualizations")
                        .HasForeignKey("EventPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_event_visualizations_event_plans_event_plan_id");

                    b.Navigation("EventPlan");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.AiInvitation", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.EventPlan", "EventPlan")
                        .WithMany("AiInvitations")
                        .HasForeignKey("EventPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_invitations_event_plans_event_plan_id");

                    b.Navigation("EventPlan");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.BookingRequest", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.Client", "Client")
                        .WithMany("BookingRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_requests_clients_client_id");

                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "DisputedByUser")
                        .WithMany("DisputedBookingRequests")
                        .HasForeignKey("DisputedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_booking_requests_users_disputed_by_user_id");

                    b.HasOne("Planura.Core.Domain.Entities.EventPlan", "EventPlan")
                        .WithMany("BookingRequests")
                        .HasForeignKey("EventPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_requests_event_plans_event_plan_id");

                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "ResolvedByAdmin")
                        .WithMany("ResolvedBookingRequests")
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_booking_requests_users_resolved_by_admin_id");

                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("BookingRequests")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_requests_vendors_vendor_id");

                    b.HasOne("Planura.Core.Domain.Entities.VendorPackage", "VendorPackage")
                        .WithMany("BookingRequests")
                        .HasForeignKey("VendorPackageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_booking_requests_vendor_packages_vendor_package_id");

                    b.Navigation("Client");

                    b.Navigation("DisputedByUser");

                    b.Navigation("EventPlan");

                    b.Navigation("ResolvedByAdmin");

                    b.Navigation("Vendor");

                    b.Navigation("VendorPackage");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.BookingRequest", "BookingRequest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_status_history_booking_requests_booking_request_id");

                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "ChangedByUser")
                        .WithMany("BookingStatusChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_booking_status_history_users_changed_by_user_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Client", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Client")
                        .HasForeignKey("Planura.Core.Domain.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.EventPlan", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.Client", "Client")
                        .WithMany("EventPlans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_plans_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.EventPlanItem", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.EventPlan", "EventPlan")
                        .WithMany("Items")
                        .HasForeignKey("EventPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_plan_items_event_plans_event_plan_id");

                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("EventPlanItems")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_plan_items_vendors_vendor_id");

                    b.HasOne("Planura.Core.Domain.Entities.VendorPackage", "VendorPackage")
                        .WithMany("EventPlanItems")
                        .HasForeignKey("VendorPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_event_plan_items_vendor_packages_vendor_package_id");

                    b.Navigation("EventPlan");

                    b.Navigation("Vendor");

                    b.Navigation("VendorPackage");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.BookingRequest", "BookingRequest")
                        .WithMany("Payments")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_booking_requests_booking_request_id");

                    b.HasOne("Planura.Core.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_clients_client_id");

                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_vendors_vendor_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("Client");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.PortfolioLink", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("PortfolioLinks")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_links_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.PortfolioMedia", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("PortfolioMedia")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_media_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Review", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.BookingRequest", "BookingRequest")
                        .WithOne("Review")
                        .HasForeignKey("Planura.Core.Domain.Entities.Review", "BookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_booking_requests_booking_request_id");

                    b.HasOne("Planura.Core.Domain.Entities.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_clients_client_id");

                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Reviews")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_vendors_vendor_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("Client");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.ReviewResponse", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.Review", "Review")
                        .WithOne("Response")
                        .HasForeignKey("Planura.Core.Domain.Entities.ReviewResponse", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_responses_reviews_review_id");

                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("ReviewResponses")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_responses_vendors_vendor_id");

                    b.Navigation("Review");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("Vendors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vendors_service_categories_category_id");

                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "User")
                        .WithOne("Vendor")
                        .HasForeignKey("Planura.Core.Domain.Entities.Vendor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendors_users_user_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorAvailability", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.BookingRequest", "BookingRequest")
                        .WithMany("VendorAvailability")
                        .HasForeignKey("BookingRequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vendor_availability_booking_requests_booking_request_id");

                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Availability")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_availability_vendors_vendor_id");

                    b.Navigation("BookingRequest");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorPackage", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Packages")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_packages_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorVerification", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "ReviewedByAdmin")
                        .WithMany("ReviewedVendorVerifications")
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vendor_verifications_users_reviewed_by_admin_id");

                    b.HasOne("Planura.Core.Domain.Entities.Vendor", "Vendor")
                        .WithMany("Verifications")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_verifications_vendors_vendor_id");

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorVerificationDocument", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.VendorVerification", "VendorVerification")
                        .WithMany("Documents")
                        .HasForeignKey("VendorVerificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_verification_documents_vendor_verifications_vendor_verification_id");

                    b.Navigation("VendorVerification");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorVerificationHistory", b =>
                {
                    b.HasOne("Planura.Core.Domain.Entities.ApplicationUser", "ChangedByAdmin")
                        .WithMany("VendorVerificationChanges")
                        .HasForeignKey("ChangedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vendor_verification_history_users_changed_by_admin_id");

                    b.HasOne("Planura.Core.Domain.Entities.VendorVerification", "VendorVerification")
                        .WithMany("History")
                        .HasForeignKey("VendorVerificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_verification_history_vendor_verifications_vendor_verification_id");

                    b.Navigation("ChangedByAdmin");

                    b.Navigation("VendorVerification");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BookingStatusChanges");

                    b.Navigation("Client");

                    b.Navigation("DisputedBookingRequests");

                    b.Navigation("Notifications");

                    b.Navigation("ResolvedBookingRequests");

                    b.Navigation("ReviewedVendorVerifications");

                    b.Navigation("Vendor");

                    b.Navigation("VendorVerificationChanges");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.BookingRequest", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Review");

                    b.Navigation("StatusHistory");

                    b.Navigation("VendorAvailability");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Client", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("EventPlans");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.EventPlan", b =>
                {
                    b.Navigation("AiEventVisualizations");

                    b.Navigation("AiInvitations");

                    b.Navigation("BookingRequests");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Review", b =>
                {
                    b.Navigation("Response");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("BookingRequests");

                    b.Navigation("EventPlanItems");

                    b.Navigation("Packages");

                    b.Navigation("PortfolioLinks");

                    b.Navigation("PortfolioMedia");

                    b.Navigation("ReviewResponses");

                    b.Navigation("Reviews");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorPackage", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("EventPlanItems");
                });

            modelBuilder.Entity("Planura.Core.Domain.Entities.VendorVerification", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
