using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Planura.Core.Application.Abstraction.Storage;
using Planura.Shared.Errors.Models;

namespace Planura.Infrastructure.Storage
{
    public class LocalFileStorageService : IFileStorageService
    {
        private static readonly IReadOnlyDictionary<string, byte[]> ImageSignatures = new Dictionary<string, byte[]>
        {
            ["image/jpeg"] = new byte[] { 0xFF, 0xD8, 0xFF },
            ["image/png"] = new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A }
            // image/webp is checked separately (RIFF....WEBP container, not a fixed prefix).
        };

        private static readonly IReadOnlyDictionary<string, byte[]> DocumentSignatures = new Dictionary<string, byte[]>
        {
            ["application/pdf"] = new byte[] { 0x25, 0x50, 0x44, 0x46 },
            ["image/jpeg"] = new byte[] { 0xFF, 0xD8, 0xFF },
            ["image/png"] = new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A }
        };

        private readonly IWebHostEnvironment _env;
        private readonly IConfiguration _configuration;

        public LocalFileStorageService(IWebHostEnvironment env, IConfiguration configuration)
        {
            _env = env;
            _configuration = configuration;
        }

        public async Task<StoredFile> SaveAsync(Stream content, string fileName, string contentType, FileStorageArea area, CancellationToken ct = default)
        {
            var length = content.Length;
            ValidateFile(contentType, length, area);

            var buffer = new byte[Math.Min(length, 16)];
            var read = await content.ReadAsync(buffer.AsMemory(0, buffer.Length), ct);
            content.Position = 0;
            ValidateSignature(contentType, buffer.AsSpan(0, read), area);

            var extension = Path.GetExtension(fileName);
            var storedName = $"{Guid.NewGuid():N}{extension}";
            var rootPath = GetRootPath(area);
            Directory.CreateDirectory(rootPath);

            var fullPath = Path.Combine(rootPath, storedName);
            await using (var fileStream = new FileStream(fullPath, FileMode.CreateNew, FileAccess.Write))
            {
                await content.CopyToAsync(fileStream, ct);
            }

            return new StoredFile
            {
                StoredPath = storedName,
                ContentType = contentType,
                PublicUrl = area == FileStorageArea.PublicImages ? GetPublicUrl(storedName) : null
            };
        }

        public Task<Stream> OpenReadAsync(string storedPath, FileStorageArea area, CancellationToken ct = default)
        {
            var fullPath = GetFullPath(storedPath, area);
            if (!File.Exists(fullPath))
            {
                throw new NotFoundExeption("File", storedPath);
            }

            Stream stream = new FileStream(fullPath, FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize: 4096, useAsync: true);
            return Task.FromResult(stream);
        }

        public Task DeleteAsync(string storedPath, FileStorageArea area, CancellationToken ct = default)
        {
            var fullPath = GetFullPath(storedPath, area);
            if (File.Exists(fullPath))
            {
                File.Delete(fullPath);
            }

            return Task.CompletedTask;
        }

        public string? GetPublicUrl(string storedPath)
        {
            var baseUrl = _configuration["FileStorage:PublicBaseUrl"] ?? "/uploads/vendor-images";
            return $"{baseUrl.TrimEnd('/')}/{storedPath}";
        }

        private string GetRootPath(FileStorageArea area) => area switch
        {
            FileStorageArea.PublicImages => Path.Combine(_env.WebRootPath, _configuration["FileStorage:PublicRoot"] ?? "uploads/vendor-images"),
            FileStorageArea.PrivateDocuments => Path.Combine(_env.ContentRootPath, _configuration["FileStorage:PrivateRoot"] ?? "App_Data/private-docs"),
            _ => throw new ArgumentOutOfRangeException(nameof(area))
        };

        private string GetFullPath(string storedPath, FileStorageArea area)
        {
            // storedPath is always a Guid-based file name generated by SaveAsync, never
            // caller-supplied, so there is no path-traversal surface to guard against here.
            return Path.Combine(GetRootPath(area), storedPath);
        }

        private void ValidateFile(string contentType, long length, FileStorageArea area)
        {
            var allowed = area == FileStorageArea.PublicImages ? ImageContentTypes : DocumentContentTypes;
            if (!allowed.Contains(contentType))
            {
                throw new BadRequestExeption($"Content type '{contentType}' is not allowed for this upload.");
            }

            var maxSize = area == FileStorageArea.PublicImages ? MaxImageSizeBytes : MaxDocumentSizeBytes;
            if (length <= 0 || length > maxSize)
            {
                throw new BadRequestExeption($"File size must be between 1 byte and {maxSize} bytes.");
            }
        }

        private void ValidateSignature(string contentType, ReadOnlySpan<byte> header, FileStorageArea area)
        {
            if (contentType == "image/webp")
            {
                var isWebp = header.Length >= 12
                    && header[0] == 'R' && header[1] == 'I' && header[2] == 'F' && header[3] == 'F'
                    && header[8] == 'W' && header[9] == 'E' && header[10] == 'B' && header[11] == 'P';
                if (!isWebp)
                {
                    throw new BadRequestExeption("File content does not match a valid WEBP signature.");
                }

                return;
            }

            var signatures = area == FileStorageArea.PublicImages ? ImageSignatures : DocumentSignatures;
            if (!signatures.TryGetValue(contentType, out var signature))
            {
                return;
            }

            if (header.Length < signature.Length || !header[..signature.Length].SequenceEqual(signature))
            {
                throw new BadRequestExeption($"File content does not match a valid '{contentType}' signature.");
            }
        }

        private static readonly HashSet<string> ImageContentTypes = new() { "image/jpeg", "image/png", "image/webp" };
        private static readonly HashSet<string> DocumentContentTypes = new() { "application/pdf", "image/jpeg", "image/png" };

        private long MaxImageSizeBytes => long.TryParse(_configuration["FileStorage:MaxImageSizeBytes"], out var v) ? v : 5 * 1024 * 1024;
        private long MaxDocumentSizeBytes => long.TryParse(_configuration["FileStorage:MaxDocumentSizeBytes"], out var v) ? v : 10 * 1024 * 1024;
    }
}
