using Microsoft.AspNetCore.Http;

namespace Planura.Core.Application.Abstraction.AttachementService
{
    public interface IAttachmentService
    {
        Task<string?> UploadAsynce(IFormFile file, string folderName);

        /// <summary>
        /// Saves raw, already-generated bytes (e.g. a QuestPDF-rendered contract) under wwwroot,
        /// for content that never arrives as an <see cref="IFormFile"/> upload. Returns the same
        /// kind of relative path as <see cref="UploadAsynce"/>, resolved via <see cref="ToAbsoluteUrl"/>.
        /// </summary>
        Task<string?> UploadBytesAsync(byte[] content, string fileName, string folderName);

        string? ToAbsoluteUrl(string? relativePath);

        bool Delete(string filePath);
    }
}
