<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.17" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Planura.Core.Application.Abstraction\Planura.Core.Application.Abstraction.csproj" />
    <ProjectReference Include="..\Planura.Core.Domain\Planura.Core.Domain.csproj" />
    <ProjectReference Include="..\Planura.Shared\Planura.Shared.csproj" />
    <ProjectReference Include="..\Planura.Infrastructure.Persistence\Planura.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
