<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>fef8580e-206a-4943-88fd-510daf08a85b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Planura.Apis.Controller\Planura.Apis.Controller.csproj" />
    <ProjectReference Include="..\Planura.Core.Application.Abstraction\Planura.Core.Application.Abstraction.csproj" />
    <ProjectReference Include="..\Planura.Core.Application\Planura.Core.Application.csproj" />
    <ProjectReference Include="..\Planura.Infrastructure.Persistence\Planura.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Planura.Infrastructure\Planura.Infrastructure.csproj" />
    <ProjectReference Include="..\Planura.Shared\Planura.Shared.csproj" />
  </ItemGroup>

</Project>
