<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Planura.Core.Application.Abstraction\Planura.Core.Application.Abstraction.csproj" />
    <ProjectReference Include="..\Planura.Core.Application\Planura.Core.Application.csproj" />
    <ProjectReference Include="..\Planura.Core.Domain\Planura.Core.Domain.csproj" />
    <ProjectReference Include="..\Planura.Shared\Planura.Shared.csproj" />
  </ItemGroup>

</Project>
